config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  get 'home/aqi'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=89129&distance=0&API_KEY=A164613D-B188-4762-9681-C393C49D4374'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    #Check for empty return
    if @output.empty?
      @final_output = "Error"
    else
      @final_output = @output[0]['AQI']
    end

    #Change AQI color
    if @final_output == 'Error'
      @api_color = "silver"
    elsif @final_output <= 50
      @api_color = "green"
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "orange"
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "red"
    elsif @final_output >= 201 && @final_output <= 250
      @api_color = "purple"
    elsif @final_output >= 251 && @final_output <= 300
      @api_color = "maroon"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a><%= link_to "Ozone", root_path, class: "nav-link"%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About Us", home_about_path, class: "nav-link"%>
      </li>
    </ul>

  </div>
</nav>

app/views/home/about.html.erb
<h1>About us...</h1>

<p>My name is Pablo Suar and this is my RoR Webpage using the Airnow API</p>

app/views/home/aqi.html.erb
<%= stylesheet_link_tag "aqi" %>
<div class="span-24">
                    <div class="span-20 last serviceOverview">
    <a name="aqi"></a>
    <h2 class="sectionTitle">Air Quality Index (AQI)</h2>
    <div class="sectionBody">
        <p>
            The EPA developed the AQI, which reports levels of ozone, particle pollution, and 
            other common air pollutants on the same scale. An AQI reading of 101 corresponds to a level  
            above the national air quality standard - the higher the AQI rating, the greater the health impact.
        </p>
    </div>
</div>
<div class="span-20 last serviceOverview">
    <a name="aqiColors"></a>
    <h2 class="sectionTitle">AQI colors</h2>
    <div class="sectionBody">
        <p>
            The AQI is divided into color-coded categories and each category is identified by a simple informative 
            descriptor. The descriptors are intended to convey information to the public about how air quality  
            relates to public health. The table below defines the AQI categories.
            <br>
        </p>
        <table class="aqiTable" style="width:600px">
            <tbody><tr>
                <th>AQI Numbers</th>
                <th>AQI Category (Descriptor)</th>
                <th>AQI Color</th>
                <th>&nbsp;&nbsp;Hexadecimal Color Value</th>
                <th>Category Number</th>
            </tr>
            <tr>
                <td>0 - 50</td>
                <td>Good</td>
                <td class="aqi_green">Green</td>
                <td>&nbsp;&nbsp;(00e400)</td>
                <td>1</td>
            </tr>
            <tr>
                <td>51 - 100</td>
                <td>Moderate</td>
                <td class="aqi_yellow">Yellow</td>
                <td>&nbsp;&nbsp;(ffff00)</td>
                <td>2</td>
            </tr>
            <tr>
                <td>101 - 150</td>
                <td>Unhealthy for Sensitive Groups</td>
                <td class="aqi_orange">Orange</td>
                <td>&nbsp;&nbsp;(ff7e00)</td>
                <td>3</td>
            </tr>
            <tr>
                <td>151 - 200</td>
                <td>Unhealthy</td>
                <td class="aqi_red">Red</td>
                <td>&nbsp;&nbsp;(ff0000)</td>
                <td>4</td>
            </tr>
            <tr>
                <td>201 - 300</td>
                <td>Very Unhealthy</td>
                <td class="aqi_purple">Purple</td>
                <td>&nbsp;&nbsp;(8f3f97)</td>
                <td>5</td>
            </tr>
            <tr>
                <td>301 - 500</td>
                <td>Hazardous</td>
                <td class="aqi_maroon">Maroon</td>
                <td>&nbsp;&nbsp;(7e0023)</td>
                <td>6</td>
            </tr>
        </tbody></table>        
    </div>
</div>
<div class="span-20 last serviceOverview">
    <a name="aqObs"></a>
    <h2 class="sectionTitle">Air quality observations</h2>
    <div class="sectionBody">
        <p>
        Hourly or daily observations are measured and reported to AirNow by federal, 
        state, local, and tribal air quality agencies.  Historical (daily) AQI values 
        are calculated using an averaging method, and real-time 
        AQI values are based on a surrogate calculation.
        </p>
        
        <h3 class="subSectionTitle" style="padding-top:10px">Data averaging</h3>
        <a name="dataAveraging"></a>
        The AQI reported for ground-level ozone and fine particles (PM<sub>2.5</sub>) is based on an 
        average of hourly data.  For ozone, the AQI is based on the maximum observed 8-hour 
        average from midnight to midnight.  For PM<sub>2.5</sub>, the AQI is simply the 24-hour average.  
        For AQI values reported in real-time, before a full day's data are available, the 
        AQI is based on a surrogate calculation.
        <br>
        <h3 class="subSectionTitle">Surrogate values</h3>
        <a name="surrogate"></a>
        Real-time observations are reported using a surrogate AQI value or NowCast.  
        More information about the surrogate calculations can be found at 
        <a href="https://airnow.zendesk.com/hc/en-us/articles/212303177-How-does-AirNow-make-the-Current-PM-Air-Quality-Index-AQI-maps-" target="_blank">https://airnow.zendesk.com/hc/en-us/articles/212303177-How-does-AirNow-make-the-Current-PM-Air-Quality-Index-AQI-maps-</a> 
        for PM2.5 and <a href="https://airnow.zendesk.com/hc/en-us/articles/212303237-How-are-your-ozone-maps-calculated-" target="_blank">https://airnow.zendesk.com/hc/en-us/articles/212303237-How-are-your-ozone-maps-calculated-</a> for ozone.

    </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is  the current Ozone Air Quality Index for my neighborhood in Las Vegas</p>
  <hr class="my-4">
  <p>Hit "Reload" in your web browser to update the reading</p>
  <%# <a class="btn btn-secondary btn-lg" href="#" role="button">Learn more</a> %>
  <a> <%= link_to 'Learn More', home_aqi_path, class:"btn btn-secondary" %></a> 
</div>

<br/>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
    <br>
    <%= yield %>
    </div>
  </body>
</html>